// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RenewableDashboard.Infrastructure.Data;

#nullable disable

namespace RenewableDashboard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RenewableDashboard.Core.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("ElectricityRate")
                        .HasPrecision(10, 6)
                        .HasColumnType("float(10)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SolarScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 29, 1, 18, 8, 996, DateTimeKind.Utc).AddTicks(3727),
                            ElectricityRate = 0.12,
                            Latitude = 31.0,
                            Longitude = -100.0,
                            Name = "Texas",
                            Note = "Strong solar potential, deregulated market",
                            SolarScore = 85
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 29, 1, 18, 8, 996, DateTimeKind.Utc).AddTicks(3738),
                            ElectricityRate = 0.23000000000000001,
                            Latitude = 36.700000000000003,
                            Longitude = -119.40000000000001,
                            Name = "California",
                            Note = "Highest rates, excellent incentives",
                            SolarScore = 92
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 29, 1, 18, 8, 996, DateTimeKind.Utc).AddTicks(3740),
                            ElectricityRate = 0.13,
                            Latitude = 34.0,
                            Longitude = -111.0,
                            Name = "Arizona",
                            Note = "Peak sun hours, growing market",
                            SolarScore = 95
                        });
                });

            modelBuilder.Entity("RenewableDashboard.Core.Entities.MarketSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CapacityGrowth")
                        .HasColumnType("float");

                    b.Property<double>("ElectricityPrice")
                        .HasPrecision(10, 6)
                        .HasColumnType("float(10)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("RenewableShare")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("MarketSnapshots");
                });

            modelBuilder.Entity("RenewableDashboard.Core.Entities.MarketTrend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarketSnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Price")
                        .HasPrecision(10, 6)
                        .HasColumnType("float(10)");

                    b.HasKey("Id");

                    b.HasIndex("MarketSnapshotId");

                    b.ToTable("MarketTrends");
                });

            modelBuilder.Entity("RenewableDashboard.Core.Entities.ProjectScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ActiveElectricityRate")
                        .HasColumnType("float");

                    b.Property<double>("AnnualEnergyProduction")
                        .HasColumnType("float");

                    b.Property<double>("AnnualRevenue")
                        .HasColumnType("float");

                    b.Property<double>("CapacityFactor")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("InstallCostPerW")
                        .HasColumnType("float");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ManualElectricityRate")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("NetOperatingIncome")
                        .HasColumnType("float");

                    b.Property<double>("Npv")
                        .HasColumnType("float");

                    b.Property<double>("OmCost")
                        .HasColumnType("float");

                    b.Property<double?>("PaybackPeriod")
                        .HasColumnType("float");

                    b.Property<string>("RateMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ScenarioType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("SystemSizeKw")
                        .HasColumnType("float");

                    b.Property<double>("TotalProjectCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ProjectScenarios");
                });

            modelBuilder.Entity("RenewableDashboard.Core.Entities.MarketTrend", b =>
                {
                    b.HasOne("RenewableDashboard.Core.Entities.MarketSnapshot", "MarketSnapshot")
                        .WithMany("Trends")
                        .HasForeignKey("MarketSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketSnapshot");
                });

            modelBuilder.Entity("RenewableDashboard.Core.Entities.MarketSnapshot", b =>
                {
                    b.Navigation("Trends");
                });
#pragma warning restore 612, 618
        }
    }
}
