// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RenewableDashboard.Data;

#nullable disable

namespace RenewableDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629011306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("RenewableDashboard.Data.Entities.CalculatorRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AnnualOMCost")
                        .HasColumnType("REAL");

                    b.Property<double>("AnnualRevenue")
                        .HasColumnType("REAL");

                    b.Property<double>("CapacityFactor")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ElectricityRate")
                        .HasColumnType("REAL");

                    b.Property<double>("InstallCostPerW")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationName")
                        .HasColumnType("TEXT");

                    b.Property<double>("NetOperatingIncome")
                        .HasColumnType("REAL");

                    b.Property<double>("Npv")
                        .HasColumnType("REAL");

                    b.Property<double?>("PaybackPeriod")
                        .HasColumnType("REAL");

                    b.Property<string>("RateMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SystemSizeKw")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalProjectCost")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CalculatorRuns");
                });

            modelBuilder.Entity("RenewableDashboard.Data.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("RenewableDashboard.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ElectricityRate")
                        .HasColumnType("REAL");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SolarScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ElectricityRate = 0.14000000000000001,
                            Latitude = 31.0,
                            Longitude = -99.0,
                            Name = "Texas",
                            Note = "Strong wind and solar development potential",
                            SolarScore = 8.5
                        },
                        new
                        {
                            Id = 2,
                            ElectricityRate = 0.22,
                            Latitude = 36.700000000000003,
                            Longitude = -119.40000000000001,
                            Name = "California",
                            Note = "High electricity prices and strong solar market",
                            SolarScore = 9.1999999999999993
                        },
                        new
                        {
                            Id = 3,
                            ElectricityRate = 0.13,
                            Latitude = 34.200000000000003,
                            Longitude = -111.7,
                            Name = "Arizona",
                            Note = "Excellent solar resource availability",
                            SolarScore = 9.5
                        });
                });

            modelBuilder.Entity("RenewableDashboard.Data.Entities.MarketSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CapacityGrowth")
                        .HasColumnType("REAL");

                    b.Property<double>("RenewableShare")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MarketSummaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityGrowth = 8.5,
                            RenewableShare = 32.0
                        });
                });

            modelBuilder.Entity("RenewableDashboard.Data.Entities.MarketTrendPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MarketTrendPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Month = "2024-01",
                            Price = 0.16500000000000001,
                            Sequence = 0
                        },
                        new
                        {
                            Id = 2,
                            Month = "2024-02",
                            Price = 0.16600000000000001,
                            Sequence = 1
                        },
                        new
                        {
                            Id = 3,
                            Month = "2024-03",
                            Price = 0.16800000000000001,
                            Sequence = 2
                        },
                        new
                        {
                            Id = 4,
                            Month = "2024-04",
                            Price = 0.17000000000000001,
                            Sequence = 3
                        },
                        new
                        {
                            Id = 5,
                            Month = "2024-05",
                            Price = 0.17299999999999999,
                            Sequence = 4
                        },
                        new
                        {
                            Id = 6,
                            Month = "2024-06",
                            Price = 0.17799999999999999,
                            Sequence = 5
                        },
                        new
                        {
                            Id = 7,
                            Month = "2024-07",
                            Price = 0.18099999999999999,
                            Sequence = 6
                        },
                        new
                        {
                            Id = 8,
                            Month = "2024-08",
                            Price = 0.182,
                            Sequence = 7
                        },
                        new
                        {
                            Id = 9,
                            Month = "2024-09",
                            Price = 0.17899999999999999,
                            Sequence = 8
                        },
                        new
                        {
                            Id = 10,
                            Month = "2024-10",
                            Price = 0.17599999999999999,
                            Sequence = 9
                        },
                        new
                        {
                            Id = 11,
                            Month = "2024-11",
                            Price = 0.17399999999999999,
                            Sequence = 10
                        },
                        new
                        {
                            Id = 12,
                            Month = "2024-12",
                            Price = 0.17499999999999999,
                            Sequence = 11
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
