// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RenewableDashboard.Web.Data;

#nullable disable

namespace RenewableDashboard.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629011218_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("RenewableDashboard.Web.Models.CalculationSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActiveElectricityRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualRevenue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ManualElectricityRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetOperatingIncome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Npv")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PaybackPeriodYears")
                        .HasColumnType("TEXT");

                    b.Property<string>("RateMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalProjectCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CalculationSnapshots");
                });

            modelBuilder.Entity("RenewableDashboard.Web.Models.LocationInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ElectricityRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SolarScore")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LocationInsights");
                });

            modelBuilder.Entity("RenewableDashboard.Web.Models.MarketSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CapacityGrowth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ElectricityPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RenewableShare")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MarketSnapshots");
                });

            modelBuilder.Entity("RenewableDashboard.Web.Models.MarketTrendPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarketSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketSnapshotId");

                    b.ToTable("MarketTrendPoints");
                });

            modelBuilder.Entity("RenewableDashboard.Web.Models.MarketTrendPoint", b =>
                {
                    b.HasOne("RenewableDashboard.Web.Models.MarketSnapshot", "MarketSnapshot")
                        .WithMany("Trend")
                        .HasForeignKey("MarketSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketSnapshot");
                });

            modelBuilder.Entity("RenewableDashboard.Web.Models.MarketSnapshot", b =>
                {
                    b.Navigation("Trend");
                });
#pragma warning restore 612, 618
        }
    }
}
